AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys IBM InfoSphere DataStage as an Amazon EKS cluster in a new VPC. This template creates EC2 instances and related resources. You will be billed for the AWS resources used if you create a stack from this template. (qs-1pjbembrj)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC network configuration
      Parameters:
      - AvailabilityZones
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PrivateSubnet3CIDR
      - VPCCIDR
      - RemoteAccessCIDR
    - Label:
        default: Cluster configuration
      Parameters:
      - KeyPairName
      - DSClientInstanceType
      - NodeInstanceType
      - AdditionalEKSAdminArns
    - Label:
        default: License configuration
      Parameters:
      - IBMDataStageICN
      - IBMDataStagePartNumber
      - IBMDataStageClientICN
      - IBMDataStageClientPartNumber
      - LicenseAgreement
    - Label:
        default: DataStage application configuration
      Parameters:
      - IISPassword
      - ResourceTag
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
    ParameterLabels:
      AdditionalEKSAdminArns:
        default: Additional EKS admin ARNs
      AvailabilityZones:
        default: Availability Zones
      DSClientInstanceType:
        default: InfoSphere DataStage Windows Client instance type
      IBMDataStageClientICN:
        default: IBM Customer Number for InfoSphere DataStage and QualityStage client
      IBMDataStageClientPartNumber:
        default: InfoSphere DataStage and QualityStage client part number
      IBMDataStageICN:
        default: IBM Customer Number for InfoSphere DataStage
      IBMDataStagePartNumber:
        default: InfoSphere DataStage part number
      IISPassword:
        default: IIS password
      KeyPairName:
        default: SSH key pair name
      LicenseAgreement:
        default: License agreement
      NodeInstanceType:
        default: Worker nodes instance type
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private subnet 3 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Remote access CIDR
      ResourceTag:
        default: Resource tag
      VPCCIDR:
        default: VPC CIDR

Parameters:
  AdditionalEKSAdminArns:
    Default: ''
    Description: '[OPTIONAL] Comma separated list of IAM users/roles to be granted admin access to the EKS cluster'
    Type: CommaDelimitedList
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. Three Availability Zones are required for this deployment, and the logical order of your selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  DSClientInstanceType:
    AllowedValues:
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
    ConstraintDescription: Must contain valid instance type
    Default: t3.xlarge
    Description: Type of EC2 instance for the DataStage Windows Client instance
    Type: String
  IBMDataStageClientICN:
    AllowedPattern: '[0-9]+'
    Description: The IBM Customer Number (ICN) listed in your Proof of Entitlement for InfoSphere DataStage and QualityStage client.
    NoEcho: true
    Type: String
  IBMDataStageClientPartNumber:
    AllowedPattern: '[a-zA-Z0-9]+'
    Description: The IBM part number associated with your InfoSphere DataStage and
      QualityStage client license.
    Type: String
  IBMDataStageICN:
    AllowedPattern: '[0-9]+'
    Description: The IBM Customer Number (ICN) listed in your Proof of Entitlement
      for InfoSphere DataStage.
    NoEcho: true
    Type: String
  IBMDataStagePartNumber:
    AllowedPattern: '[a-zA-Z0-9]+'
    Description: The IBM part number associated with your InfoSphere DataStage license.
    Type: String
  IISPassword:
    Description: 'The password to be set on the DataStage application for the user name "isadmin".'
    Type: String
    MinLength: 8
    MaxLength: 20
    NoEcho: true
    AllowedPattern: '(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[\p{Punct}])([0-9a-zA-Z\p{Punct}]+)'
    ConstraintDescription: Must be 8-20 characters, containing one number, one special
      character, one lower case and one upper case character.
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  LicenseAgreement:
    Description: Choose Accept to acknowledge that you have read and agree to the license terms for IBM InfoSphere DataStage v11.7.1 (http://ibm.biz/isds1171) and IBM Infosphere DataStage and Quality Stage Designer v11.7.1 (http://ibm.biz/isdsc1171).
    Type: String
    Default: '-'
    AllowedValues:
      - I agree
      - '-'
  NodeInstanceType:
    AllowedValues:
      - t3.xlarge
      - t3.2xlarge
      - t3a.xlarge
      - t3a.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m5.metal
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5a.16xlarge
      - m5a.24xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
      - r5.24xlarge
      - r5.metal
      - r5a.large
      - r5a.xlarge
      - r5a.2xlarge
      - r5a.4xlarge
      - r5a.12xlarge
      - r5a.24xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.18xlarge
      - z1d.large
      - z1d.xlarge
      - z1d.2xlarge
      - z1d.3xlarge
      - z1d.6xlarge
      - z1d.12xlarge
      - z1d.metal
    ConstraintDescription: Must contain valid instance type
    Default: m5.xlarge
    Description: Amazon EKS worker node EC2 instance type.
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: '10.0.0.0/19'
    Description: The CIDR block for the private subnet located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: The CIDR block for the private subnet located in Availability Zone 2.
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.64.0/19
    Description: The CIDR block for the private subnet located in Availability Zone 3.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: The CIDR block for the public subnet located in Availability Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.160.0/20
    Description: The CIDR block for the public subnet located in Availability Zone 3.
    Type: String
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-ibm-infosphere-datastage/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the instances. We recommend
      that you set this value to a trusted IP range.
    Type: String
  ResourceTag:
    AllowedPattern: '[a-z0-9]+'
    ConstraintDescription: Non-empty. Must be lower case letters and numbers only.
    Default: ds1
    Description: This will be used to label AWS resources and the DataStage Kubernetes
      namespace. Ensure that every InfoSphere DataStage deployment on your AWS account
      uses a unique resource tag.
    Type: String
  VPCCIDR:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
Rules:
  LicenseAgreementRule:
    Assertions:
      - Assert: !Contains
          - - I agree
          - !Ref 'LicenseAgreement'
        AssertDescription: User must agree to the terms of the license agreement
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/submodules/quickstart-aws-vpc/templates/aws-vpc.template'
      Parameters:
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        NumberOfAZs: '3'
        PrivateSubnet1ACIDR: !Ref 'PrivateSubnet1CIDR'
        PrivateSubnet2ACIDR: !Ref 'PrivateSubnet2CIDR'
        PrivateSubnet3ACIDR: !Ref 'PrivateSubnet3CIDR'
        PrivateSubnetATag3: 'kubernetes.io/role/internal-elb=1'
        PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
        PublicSubnet3CIDR: !Ref 'PublicSubnet3CIDR'
        PublicSubnetTag3: 'kubernetes.io/role/elb=1'
        VPCCIDR: !Ref 'VPCCIDR'
  DataStageExistingVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/ibm-datastage.template.yaml'
      Parameters:
        AdditionalEKSAdminArns: !Join [ ',', !Ref AdditionalEKSAdminArns ]
        DSClientInstanceType: !Ref DSClientInstanceType
        IBMDataStageClientICN: !Ref IBMDataStageClientICN
        IBMDataStageClientPartNumber: !Ref IBMDataStageClientPartNumber
        IBMDataStageICN: !Ref IBMDataStageICN
        IBMDataStagePartNumber: !Ref IBMDataStagePartNumber
        IISPassword: !Ref IISPassword
        KeyPairName: !Ref KeyPairName
        LicenseAgreement: !Ref LicenseAgreement
        NodeInstanceType: !Ref NodeInstanceType
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        PrivateSubnet3ID: !GetAtt VPCStack.Outputs.PrivateSubnet3AID
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        PublicSubnet3ID: !GetAtt VPCStack.Outputs.PublicSubnet3ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        ResourceTag: !Ref ResourceTag
        VPCCIDR: !GetAtt VPCStack.Outputs.VPCCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
Outputs:
  BastionIP:
    Value: !GetAtt DataStageExistingVPCStack.Outputs.BastionIP
  DataStageClientPublicDnsName:
    Value: !GetAtt DataStageExistingVPCStack.Outputs.DataStageClientPublicDnsName
  LaunchpadURL:
    Value: !GetAtt DataStageExistingVPCStack.Outputs.LaunchpadURL
