global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-ibm-infosphere-datastage
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  ds-master-3az:
    parameter_input: ds-master-3az-parameters.json
    template_file: ibm-datastage-master.template
    regions:
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-1
      #- eu-west-2
      - us-east-1
      - us-east-2
      - us-west-2
